### PR TITLE
tweaked the previous PR as requested with the new base

### PR DESCRIPTION
**Pull request by Aureliolo**
Hope no changes i made fell through the cracks... better test this one before merging :p

### CODE REVIEW

**Review by JJM152 — APPROVED** [review]
The clown costume is funny as hell.

**Comment by panslothda** [comment]
:DI tried. And yes my git game is not strong. I work in IT but my job is to administrate servers and virtualization stuff not mess around with git and programming although I wished I could do more of that. that's why it took me so long for these small changes. needed to remember how syntax works etc. haven't touched this kinda thing in quite a bit.

**Comment by JJM152** [comment]
You did great. Continue to contribute :+1:

**Comment by panslothda** [comment]
Will do when I get an idea :)

**Pull request merged**
