### PR TITLE
Auto build

### PR DESCRIPTION
**Pull request by ezsh**
P.S. Please make sure to disable builds for PRs, because any PR can print out your mega.nz login credentials.

### CODE REVIEW

**Comment by JJM152** [comment]
Yeah, I looked at this, sorry for not updating the comments. Just pausing to read through the relevant provider documentation, which ended up giving me too many ideas I think.

I think in a perfect world, something like this would happen:

**Tagged Release**
- Zip file and push to file hosting service (mega, mediafire, google, whatever)
- Put unzipped file at some web hosting page (latest/index.html)

**Every commit**
- Put unzipped file at some web hosting page. (in-dev/index.html)

Just let me stew on how I want to handle this a bit more. :)

**Comment by JJM152** [comment]
I may stop embedding resources into the html and start loading them externally (and depending on those resources, this might end up being a very large archive). 

Anyway, it looks like a trivial thing to do in the after: handler as there is already a 7z binary available.

I'm still reading up on how artefact pushing works atm and considering how I may want to handle this in the future.

**Comment by ezsh** [comment]
> I may stop embedding resources into the html and start loading them externally…

Aha, then it makes sence to put bundling/uploading commands into a file and call it from appveyour.yml

**Comment by ezsh** [comment]
So I went ahead and put the publishing code in its own script file. One can add images and other required files changing the `pack_output()` function. I don't think one can find publishing providers we need in the usual CI services assortments (as least this is my impression after checking Travis and AppVeyour).

**Comment by ezsh** [comment]
Ping?

**Comment by ezsh** [comment]
It's in a conflict again :( And that happens when you work with feature branches as well. That is why I am impatient about this PR.

**Comment by JJM152** [comment]
eh eh eh??? how is it in conflict? I thought other than deleting/ignoring Queen.html it was all file additions?

Part of the reason why I pushed it back until after 0.8 was because I thought I **could** sit on it until then.

**Comment by ezsh** [comment]
Exectly because of deleting the Queen.html. When its contents change, git "recalls" that it was asked to delete file with another hash and falls into a state of conflict.

**Comment by JJM152** [comment]
Ah, I thought it was something major maybe... not just annoying.

Because I know that there will probably be bugfixes off 0.8 before 0.9 gets ready, particularly since I am going on vacation and won't be able to code much (if at all), I went and created a bugfix branch for just that purpose. 

I'm not keen to do feature and develop branches or anything that heavy. Seems like a waste of time to me. Whatever gets fixed in 0.8 from here on out we'll just merge down to master for the next release.

I should still be around for another day or two here, but after that only in US EST in the evenings to look at stuff and (maybe) do some minor fixes.

**Comment by ezsh** [comment]
OMG, it got merged! Thank you so much!

P.S. Maybe you would update README.md with a link to the directory the builds are published to?

**Comment by JJM152** [comment]
Yeah, will do when I get that set up. I was using media fire before (it's pants) so I just opened up a mega.nz account. I'll get that all hooked up before I go on leave.

**Pull request merged**
