### PR TITLE
Further fixes for inventory refactor bugs

### PR DESCRIPTION
**Pull request by ezsh**

### CODE REVIEW

**Comment by ezsh** [comment]
https://github.com/JJM152/Queen/issues/58#issuecomment-426021079 lists what I've tested and hopefully fixed.

**Comment by JJM152** [comment]
Hey, I'm not really a javascript programmer, but I specifically took TakeItem out because it has the possibility of deleting the item at 0 charges while I still need to call methods on it. Shouldn't this cause a null reference or at least break the further calls?

**Comment by ezsh** [comment]
Neither am I, but [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete) says that the item object will be valid until we release the last reference to it. Of course, calling `Charges()` will return zero, and that might be considered wrong, because here it is, the charge. But strictly speaking, it is not in the inventory anymore, thus returning 0 is technically correct.

In the previous version `TakeItem()` looked as follows:
```js
o.RemoveCharges(1);
if (o.Charges() <= 0) this.DeleteItem(o);
```
and the `DeleteItem()` call was succesfull, creating a property in the inventory with 0 charges (another bug; fixed by this PR). Sure, GC is not instanteneous, but nevertheless that was kind of working.

P.S. Of course the charges test and the call to `DeleteItem()` is superfluous.

**Comment by ezsh** [comment]
There is a conceptual difference between an item in the inventory, and the same item outside of it, which is not reflected in the `Item` classes. Maybe things would be better if I indeed used the Flyweight patter for the items. Well, in C++ I would do that in no-time (no, I would use a standard smart pointer with reference counting) :) But here we don't have compiler to help and thus addind another layer and maintaining it seem to me to be too costly. Maybe we can implement `Charges()` in the `Item` class and make it ask the manager if manager is set and return unity otherwise? Then we can simply create the item object for a taken out item (a reel or whatever we are operating with) passing `null` as the inventory manager and it will be truly detached from the inventory?

**Comment by JJM152** [comment]
tbh, Charges probably does belong in the Item class because it's actually used as an item count. Can be a future refactor though I guess.

**Pull request merged**
