### PR TITLE
Inventory cleanup

### PR DESCRIPTION
**Pull request by ezsh**
Not thoroughly tested yet, but you can get the idea. I try to keep the Player and Item interfaces intact.

### CODE REVIEW

**Comment by JJM152** [comment]
Great, I'll merge this and start testing.

If you feel up for it, I could use some help on #43 - considering you just refactored the inventory system, you know it better than I do right now.

Basically, I am thinking something simple:

(non gear pages)
Put a start next to the item count (empty). If clicked, it lights up. That item always appears at the top of the page in sort order.
Next sort after the above, is done alphabetically.

On the gear page, implement an expand/collapse panel for the non-worn/equiped items. Sort entries in this panel alphabetically.

**Comment by ezsh** [comment]
Thanks! I could have merged the fixup commit... 

As for the inventory list, yesm I can do the favorites/sorting stuff, and also I would add a "throw out" button.

**Comment by JJM152** [comment]
Sure, but no throwing out of quest items or locked clothing :)

**Comment by JJM152** [comment]
I just added you as a collaborator to this project (just accept the link that got sent to you).

So, you can merge your own commits now, but try to let me review them at least before doing so and of course open up an issue for an enhancement for discussion prior to implementing stuff.

Basically just common sense stuff I think, you seem like a chill guy so I'm not worried.

**Comment by ezsh** [comment]
OK, thanks. I think you can use a GitHub settings in the repository to force require an approval before merging a PR (an you will not be affected because you are a repo admin).

**Comment by JJM152** [comment]
I'll look into that, I was under the impression it forced you to commit to a non protected branch and then merge from there. I **guess** I'll read the documentation. Sheesh :)

**Pull request merged**
