### PR TITLE
Favorites in shops

### PR DESCRIPTION
**Pull request by ezsh**

### CODE REVIEW

**Comment by ezsh** [comment]
Requested a review because the first commit is questionable. My motivation: items factory could read item charges from the data lists and append the charges to the inventory on creation, which would be a bug. A better way to solve that would be extracting NPCs inventory from the PlayerState and then NPC will be able to use their own InventoryManager instances. Something as follows:

```js
class CharachterState {
     this.Inventory = {};
};

class PlayerState extends CharachterState {
    // wardrobe, etc.
};

GameState {
      this.NPCs; // @type CharachterState
      this.Player; // @type PlayerState
}; 
```

**Comment by JJM152** [comment]
Hmm. 

I think, regardless of if the NPC inventory is in the PlayerState or another class, the shop data needs to be saved between sessions otherwise you can reset the shops at will. That's probably the only thing that jumps out at me.

Other than that I don't see any problem with it, I believe Examine() passes a reference to the player object, so that should still work just fine. 

The favorite icon in shops looks fine, but reminds me that I want to add tooltips to the game just so that I can have it say, "Favorite Item" on mouse over.  This could be done with some css and a twine widget I think pretty easily. I'll think about that for later...

Rambling over now... 

Is this ready to go or do you want to add more to it now?

**Comment by JJM152** [comment]
> Hmm, but the icon is there to give the hint quickly, would hovering an item work that way?

I meant hovering over the star, not the item. Otherwise people might be confused as to why there is a star there.

Tool tips are something I keep meaning to add to the game, simply because it would be nice to have additional information appear explaining game mechanics and ui elements, but it's also really low down my priority list.

Anyway, I'll merge this guy and move on for now... cheers!

**Comment by ezsh** [comment]
Thanks!

**Pull request merged**
