### PR TITLE
Refactor inventory tabs and add tabs to the journal.

### PR DESCRIPTION
**Pull request by ezsh**
Implements tabs as rows of buttons. 

Pros: 
1. Adding a new tab does not require changing code for other tabs any more.
2. Content widget does not need to care about headers (the tabs).

Cons:
1. Tabs styling does not ~perfectly~ fit into the rest of the UI.

Screenshots:

inventory
journal-active-quests
journal-completed-quests

This contributes to #40;

### CODE REVIEW

**Comment by ezsh** [comment]
Maybe they look better this way?
inventory-pseudo-links

**Comment by ezsh** [comment]
PR update: track earned money and skill test results and display them in the journal.

**Comment by ezsh** [comment]
Rebased.

**Comment by ezsh** [comment]
Checked the screenshots again, and I have to admit I really liked the first look. Maybe we'd better make store buttons rectangular and use that tabs style? In my opinion, it fits better to the chosen colour scheme. Although, its cyberpunk reflexes do not fit in the setting.

**Comment by JJM152** [comment]
I'm not too fussed by it if you want to redo the button css. Those screenshots look fine and I was actually looking at the shop interface today and thinking that I didn't like the buttons any more either.

**Comment by ezsh** [comment]
What do you think?
square-buttons

P.S.Other UI elements (hints in the shops, for example) need to be changed if we go this rectangular way...
P.P.S. Fixed layout for disabled buttons later than took the screenshot.

**Comment by JJM152** [comment]
Very cool. I just had to make a slight adjustment so that some skill checks would show up. It's very nifty framework for tracking stuff.

**Comment by ezsh** [comment]
Oh, great! There are a number of visual problems left. In particular, the "Back" button in the item examination widget is placed weirdly now. This I will try to fix. Also pMeter display style does differ much from the buttons. Perhaps we can replace "*" with the sharp star symbols, as those used for the favorites? Or another symbol...

**Pull request merged**
