### PR TITLE
Use 'null' instead of '0' for marking equipment slots as empty.

### PR DESCRIPTION
**Pull request by ezsh**

### CODE REVIEW

**Comment by ezsh** [comment]
The PR misses corrections for tests in the quest and job engines.

**Comment by ezsh** [comment]
Rebased but untested.

**Comment by ezsh** [comment]
Rebased

**Comment by JJM152** [comment]
has this been tested yet?

**Comment by ezsh** [comment]
No, I did not test it after the resurrection and rebasing.

**Comment by ezsh** [comment]
Rebased, updated, and slightly tested.

**Pull request merged**
