### PR TITLE
Revert "Tune bust XP costs to make them proportional to breast volume"

### PR DESCRIPTION
**Pull request by JJM152**
Reverts JJM152/Queen#136

Played around with this some, just some comments:

- Like the new display.
- The initial step costing is too high and breaks the gameplay flow.

I didn't have time to take this part and work out the correct algorithm to get the results I wanted, so I'm reverting this for now.

### CODE REVIEW

**Comment by ezsh** [comment]
What do you want to achieve? Just lower the step between flat and some breast?

**Comment by JJM152** [comment]
Pretty much yes.

From my perspective it's an early game pacing issue with player feedback - the bust attribute is already hard to raise early on in the game, so it'll be frustrating for people trying to complete the first Bimbo quest - even if it DOES eventually even out after the first step, the players will not know that, particularly since it'd be out of lock step with ass and hips which can get frequent gains through the experimentation job.

I would be fine actually with converting bust, hips and ass to the same formula. I can then go and generate a graph of that and tweak the body growth effects so that they grant XP in the portion that I want.

**Comment by ezsh** [comment]
We should probably not assume that pecks volume is zero.

> with converting bust, hips and ass to the same formula.

Same formula? How is that possible? While ass checks are spheroids and thus similar, the hips volume is a different measurement (circumference, a length) and includes the ass. The model for hips is therefore not a parabolic function.

**Comment by JJM152** [comment]
Right, I was thinking simplistically that I want the same XP stepping. To me, everything is essentially arbitrary and just engineered to get the effect I want from the player interactions, but you're trying to create a non-arbitrary scale that models something (specifically breast volume).

From my point of view, which is mainly just balancing the game so that quests and jobs and such make some sort of sense, it's a lot easier if the conversion of XP into points, numerically amount to similar values on a scale of 1-100, regardless of what that translates into in terms of descriptions. Does that make sense?

**Comment by ezsh** [comment]
Some people (myself included) need a level of realism, a rational seed, to play a game (any game). Seems like we have divergent visions here. And a kind of mass conservation law is the very basic foundation which can give a strong feeling of reality. So, while linear scale for XP <-> body part size is convenient for planning and balancing gameplay, the other side of this simple relation strikes those like me. Is there a compromise?

**Pull request merged**
