### PR TITLE
Add a quest to unlock inventory favorites. Closes #99.

### LINKED ISSUE #99: Quest to enable favourites
Add a quest to enable favourites in inventory.

The idea: when inventory list grows to contain more than, say, 15 -- 20 types of items, opening the inventory results in an intermediate passage (only once) with a note that there are too many different items in the locker and it is hard to keep them organised. Then a quest with Julius uncovers to obtain additional boxes and shelves for the cabin.
Julius will of course request to participate in his human experimentations for a few days and keep him in a mood (happy (80)? 85?) for a week to make the boxes. 

Completing the quest unlocks favourites in the inventory and shops.

### PR DESCRIPTION
**Pull request by ezsh**
The gameplay gets the following changes: when inventory contains too
many items (>250) or too many items types (>50), players get a
message about that when opening inventory. Additionally, when number of
items is > 500, on each opening some items get lost (up to 25% of the
randomly selected item, accounting for items charges. I.e. the items
with most charges will be most likely lost). When player complete a
quest with Julius, favorites button is enabled and the messages do not
pop up anymore.

### CODE REVIEW

**Comment by ezsh** [comment]
While this basically works, I'm not happy about two things:
1. I've added a function to the quest definition ("ON_DAY_PASSED"). Maybe the trick could be done in a declarative way, but for that we need a way to address quest or job properties in the declarative way.
2. There is no connection to the human experimentation job from the quest due to the similar reason. It would be logical to refer to the days passed since the last job cooldown, but there is no way to do so. 

But there is a todo comment at the beginning of the `QuestEngine` about possible merging the quest and job engines, and thus I did not want to make any big changes to the `QuestEngine` class.

**Comment by ezsh** [comment]
Rebased.

**Comment by JJM152** [comment]
> While this basically works, I'm not happy about two things:
> 
> 1. I've added a function to the quest definition ("ON_DAY_PASSED"). Maybe the trick could be done in a declarative way, but for that we need a way to address quest or job properties in the declarative way.
> 2. There is no connection to the human experimentation job from the quest due to the similar reason. It would be logical to refer to the days passed since the last job cooldown, but there is no way to do so.
> 
> There is a todo comment at the beginning of the `QuestEngine` about possible merging the quest and job engines, and thus I did not want to make any big changes to the `QuestEngine` class.

Yeah, the QuestEngine class probably needs to go away, it's basically a really bad version of the already questionable JobEngine class. 

I'm not too keen for anyone to waste any time on either of these areas right now as I'm questioning if given the nature of Twine if the whole concept is even freaking valid (still considering why I made this at all). By all means add as much spackle and grit as you can to make things "work" for the odd bit of thing you're trying to accomplish but I wouldn't invest any effort into it. :)

**Comment by ezsh** [comment]
Could you elaborate, please, on these subject? What has Twine to do with that? Twee compiler? SugarCube? What would you like to achieve instead?

**Comment by ezsh** [comment]
Rebased.

**Pull request merged**
