### PR TITLE
Make speech text serif. Closes #192.

### LINKED ISSUE #192: Font for speech highlighting differs too much from the main font
font

My suggestion is as follows. If we want to set font family for a given style, which is used inside of the main text, the font family for the main text has to be set explicitly too. Or we can use only generic families (serif, sans-serif, monospace).

For my taste, oblique font would be a better choice here:
font-oblique

### PR DESCRIPTION
**Pull request by ezsh**

### CODE REVIEW

**Comment by ezsh** [comment]
My default serif/sans-serif fonts are Tinos/Arimo, and the speech renders as Verdana. It looks really bad, as they are not metrically compatible.

**Comment by JJM152** [comment]
Eh, I kind of hate the long strings of oblique text. I don't care if you want to just nuke the font face and leave the coloring intact.

**Comment by ezsh** [comment]
I see... Since you wanted it to be typeset in a different font, what about using the simple "serif"?

serif-font

**Comment by ezsh** [comment]
Or, given the definition in the SugarCube:
```css
html {
	/*
		We define the base font size and line height here as they affect the layout
		of the base page elements (i.e. `#ui-bar`, `#ui-dialog`, and `#story`).
	*/
	font: 16px/1 Helmet, Freesans, sans-serif;
}
```
We should do `font-family: Freeserif, serif;`

**Comment by ezsh** [comment]
PR updated to `font-family: Freeserif, serif;`

**Comment by JJM152** [comment]
Alright sounds good.

**Comment by ezsh** [comment]
OK, thanks!

**Pull request merged**
