### PR TITLE
Make clothing restriction actually work.

### PR DESCRIPTION
**Pull request by ezsh**
Actually undress restricted slots, not just copy items to inventory.

### CODE REVIEW

**Comment by JJM152** [comment]
for 0.8 bug fixes, merge them to the 0.8 bugfix branch for now. I'll just merge master up since it's not a big deal now, but it will become one later right?

**Comment by ezsh** [comment]
Pardon, don't quite understand what exactly do you expect from me. Do we take the usual path (PRs for bugfixes against the release branch and periodical merges of the release branch into master), or do you want me to submit 2 PRs (one for the master branch, another one for the release branch)?

**Comment by JJM152** [comment]
Yeah, sorry, I thought I had mentioned it in another comment - 
PR to 0.8 bugfix first, then to master. 

Btw, this didn't fix the issue. I'm trying to swap stockings on a character that already has them equipped and it's crashing with a null reference.

image

**Comment by ezsh** [comment]
2 PRs then. OK, thanks for the clarification!

**Pull request merged**
