### PR TITLE
Added starter lootbox

### PR DESCRIPTION
**Pull request by panslothda**
Added 2 lootboxes for the start and a selection of one for the intro1 page. Makes the start a bit easier for those that want it.
If you have balancing issues or so let me know or change directly. You dont need to add this ofc. Its just a continuation of my post on tfgames discussion regarding the easy start because I wanted it for myself :)

### CODE REVIEW

**Comment by panslothda** [comment]
Sounds good to me :) I just added a bunch of stuff for me to this because I wanted to test the new things that came out with the version without having to grind :p Since I played through most of the game with the 2 releases before each time.

I may have an hour or 2 freetime today so might be able todo this right now so it would be ready for next release if not welp will do when got time.

Anyways thanks for the feedback :)

**Comment by panslothda** [comment]
Small question I forgot to ask what about cosmetics maybe some basic hair and cosmetic on landlubber and a few (like 10) of the expensive ones for pathetic loser?

And I will add 2 costumes(new ones I will add to the game) for each of the boxes and add a few like 2 other to the basic and maybe 3 or 4 to the loser one if ok.

**Comment by JJM152** [comment]
Yeah, adding cosmetics will be fine, your idea sounds sensible. Not a big deal at all.

Costumes are cool, just make sure that none of them are set as "LEGENDARY" pieces. UNCOMMON would be best, or "COMMON" if just done for flavor.

**Comment by JJM152** [comment]
I'm probably going to push 0.4 live tonight as it's done. We can get this into 0.5 for sure.

Cheers

**Comment by panslothda** [comment]
Well what is tonight for you as in what timezone? because I finished the difficulty screen and half of the lootbox and probably will have it finished in half an hour one hour tops. Except I run into something strange.

But if you wanna release go for it. it can wait a version from my side :)

**Comment by JJM152** [comment]
Waaa I didn't know you were working on it that furiously lol!!!!

Okay, I'll wait a bit and do some more testing and finish writing the release notes, etc. I'll be around for another couple of hours!

**Comment by panslothda** [comment]
Ah thats reassuring then I take my time to come up with good costumes :) excpect a PR in around an hour to one a half hour from now on.

And not working furiosly. more while on phone with clients while on work writing a bit here and a bit there to keep my hands busy.

**Comment by panslothda** [comment]
changed. I hope i did not grant to many items in the loot boxes :/ Let me know what you think.

**Comment by JJM152** [comment]
I had an email in the repo commit history I Didn't wan't public, so I had to nuke it from orbit

**Comment by JJM152** [comment]
I see you did another fork. That's probably the easiest thing to do at this point if you're not good at git command line.

Sorry about that - I should have waited until your push.

**Pull request closed without merging**
