### PR TITLE
Split the Player class onto code and data

### PR DESCRIPTION
**Pull request by ezsh**
The class instance was a SugarCube variable and thus was serialized when
saving/loading games with all the functions code. Not only that
increased the size of the save data, but also made changing functions in
the Player class overcomplicated, as they were replaced with the loaded
from a save data code.

### CODE REVIEW

**Comment by ezsh** [comment]
I've read your post on the tfg forum, glad that you came back. While I was unsure whether you be back at all, I stopped to submit PRs and did not update this one but worked on my fork instead. The current code in the PR contains many mistakes, so please wait with detailed review. I will update once I finish and commit my current changes.

**Comment by ezsh** [comment]
PR updated.

**Comment by JJM152** [comment]
I think what I'll do is hold off and merge this into the 0.8 release tag, that way I can get something out in the next hour or so for people to play with.

cheers

**Comment by JJM152** [comment]
After I finish off the last bug I have open (assuming nothing else easy to fix pops up), I'm going to put out the 0.7b bugfix release and then move on to 0.8 where we'll be carrying this forward.

**Comment by ezsh** [comment]
Thanks!

**Comment by JJM152** [comment]
This is cool, but I'm sort of wondering about moving the Player class into a ECMA 5.1 compliant implementation. 

It sorta bugs me that I didn't consider this before merging it because I feel like I inadvertently might have screwed some people over running older browsers.

Still considering what to do.

**Comment by ezsh** [comment]
Not that I care for IE users (Internet technologies were developing due to erotic/porn since the beginning :D), but please let me know your decision because I am refactoring the item classes already using the same ES5 (I was sure that this is version 6) features. 

BTW, plan to make them *Flyweight* *Observers*, probably created either on demand or, maybe, recreated on save loading. Would you agree to merge that?

**Comment by JJM152** [comment]
That pattern is fine, like I said, I used to store the NPC objects serialized with the save game data but replaced with a halfarsed flyweight pattern. Seems fine to me.

As for the ES6 syntax, I think it's probably fine. If a lot of people complain, I can just run it backwards through a transpiler in like 10 minutes and get more or less back to ES5 compat without having to do any real work.

**Pull request merged**
