### PR TITLE
Track quest accept/complete dates

### PR DESCRIPTION
**Pull request by ezsh**
When accepting or completing a quest, set an additional quest flag to
memorize the day when it happened. The dates are shown in the journal
then, to make it look more like a personal diary.

Add new action type "QUEST" for triggers, that accept quest name
("NAME") and value ("VALUE"). The values currently are "START" to
accept a quest and "COMPLETE" to complete the quest. In additiona to
setting the quest state, this action sets the accept/complete date for
the quest.

Journal screenshots:
active
completed

WIP: I don't know yet what to do with the currently active quests when applying this update:
unknown-dates

### CODE REVIEW

**Comment by ezsh** [comment]
PR updated: `Quest.AcceptedOn()` and `Quest.CompletedOn()` return "1" (the first day onboard Salty Mermaid ) if there is no actual data and quest lists in the journal are sorted by date (newest first).

**Comment by JJM152** [comment]
Like it. Nice idea.

**Comment by ezsh** [comment]
Err... Thanks, but what to do with the same games? I thought of something like: "I decided to add dates to my journal. Unfortunately, I did not do that earlier and now I hardly remember even dates of major events after Captain Reginald ruined my life. I'm going to use approximate dates for past events to put them in order."

And then add this as an event to the game and set dates from a typical playthrough, scaled using current day and active quests.

**Comment by JJM152** [comment]
Well, if you want to go through that much work then that's up to you, but I think that the game is technically in alpha, so just putting a "????" in there and a note in the change log saying that past dates will only show up on new playthroughs is totally sufficient!

I think there's got to be some sort of diminishing returns on effort expended when considering that eventually everyone will be playing from a new save anyway. over time... except for that one person who is still playing their original save on like version 0.67, but who cares about them? :)

**Comment by ezsh** [comment]
Don't want to add this workaround (handling absent data) to the main code path, and I like such little details. So maybe I will implement the update mechanics. Just need to get that typical quest completion times.

**Pull request merged**
